### ISSUE TITLE
Question: Can I use the cargo module to have http::outgoing_requests

### ISSUE THREAD

**Issue by dipankardas011** [bytecodealliance/wasi-rs#94]
## Question
I want to perform the http outgoing request inside my Rust code

## Problem
Tokio, reqwst are not compatable

**Comment by dipankardas011** [comment]
Actually I want a example to use it in my application codebase

**Comment by dipankardas011** [comment]
If not any other crate which can help me accomplish this http request

**Comment by alexcrichton** [comment]
Yes this crate enables you to call [this function](https://docs.rs/wasi/latest/wasi/http/outgoing_handler/fn.handle.html) to perform outgoing HTTP requests. Integration with upstream crates will take time, but in the meantime you can do the WASI-specific thing.
